service:
  name: fit3036

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: ap-southeast-2

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  area:
    handler: bin/remote-area
    events: 
      - http:
          path: area
          method: post

